all: rubik.cpp
	
rubik: rubik.cpp
	g++ rubik.cpp -o rubiks -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32

rubik2: rubik2.cpp
	g++ rubik2.cpp -o rubik2 -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32 -std=c++11
	
rubik3: rubik3.cpp
	g++ rubik3.cpp -o rubik3 -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32
