all: cube.cpp triangle_sierpinski.cpp
	
cube: cube.cpp
	g++ cube.cpp -o cube -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32

triangle: triangle_sierpinski.cpp
	g++ triangle_sierpinski.cpp -o triangle_sierpinski -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32

sierpinski: sierpinski.cpp
	g++ sierpinski.cpp -o sierpinski -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32