all: cube.cpp cube2.cpp
	
cube: cube.cpp
	g++ cube.cpp -o cube -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32

cube2: cube2.cpp
	g++ cube2.cpp -o cube2 -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32