all: cube.cpp sierpenski.cpp sierpinski_point.cpp
	
cube: cube.cpp
	g++ cube.cpp -o cube -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32
	
sierpinski: sierpinski.cpp
	g++ sierpinski.cpp -o sierpinski -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32

sierpinski_point: sierpinski_point.cpp
	g++ sierpinski_point.cpp -o sierpinski_point -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32 -lglew32 -lglu32
