all: triangle.cpp triangle-gradasi.cpp
	
triangle: triangle.cpp
	g++ triangle.cpp -o triangle -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32

triangle-gradasi: triangle-gradasi.cpp
	g++ triangle-gradasi.cpp -o triangle-gradasi -Llib-mingw/ -lglfw3 -lopengl32 -lgdi32